baseURL = "https://andrii-lazarenko.com/"
defaultContentLanguage = "ru"
theme = "hugo-initio"
enableRobotsTXT = true

# Languages

[languages.ua]
  languageName = "Укр"
  title = "Андрій Лазаренко - оргетерапевт. Інтегративна психотерапія гештальт і культурно-історичного підходів"
  name = "Андрій Лазаренко"
  description = "Оргетерапевт. Інтегративна психотерапія гештальт і культурно-історичного підходів"
  email = "andrew.yeremenko@gmail.com"
  phone = "+38 066 74 39 713"
  address = "Київ, Україна"

  hpServicesTitleTranslation = "Послуги"
  ReadMoreTransl = "Читати далі..."

  contactTitleTranslation = "Контакти"
  followMeTranslation = "Соцмережі"
  keyMessage = "Головне повідомлення"
  myFriendsTitleTranslation = "Мої друзі"
  footerFormWidgetHeadline = "Підписатись"
 
  [[languages.ua.menu.main]]
    url = "/"
    name = "Головна"
    weight = 1
  [[languages.ua.menu.main]]
    url = "/post/"
    name = "Статті"
    weight = 10    
  [[languages.ua.menu.main]]
    url = "/about/"
    name = "Про мене"
    weight = 20  
  [[languages.ua.menu.main]]
    url = "#contactTitle"
    name = "Контакти"
    weight = 30   

[languages.ru]
  languageName = "Рус"
  title = "Андрей Лазаренко - оргтерапевт. Интегративная психотерапия гештальт и культурно-исторического подходов"
  name = "Андрей Лазаренко"
  description = "Оргтерапевт. Интегративная психотерапия гештальт и культурно-исторического подходов."
  email = "andrew.yeremenko@gmail.com"
  phone = "+38 066 74 39 713"
  address = "Киев, Украина"
  
  hpServicesTitleTranslation = "Услуги"
  ReadMoreTransl = "Читать далее..."
  
  contactTitleTranslation = "Контакти"
  followMeTranslation = "Соцсети"
  keyMessage = "Изнутри наружу -- путь самопознания и самосовершенстования"
  myFriendsTitleTranslation = "Мои друзья"
  footerFormWidgetHeadline = "Подписаться"

  footerTextBoxHeadline = "Cуть культурно-исторического подхода"
  footerTextBoxBody = "Возвращаясь к корням, соеденить настоящее с прошлым, ради будущего!"

  [[languages.ru.menu.main]]
    url = "/ru/"
    name = "Главная"
    weight = 1
  [[languages.ru.menu.main]]
    url = "/post/"
    name = "Статьи"
    weight = 10
  [[languages.ru.menu.main]]
    url = "/about/"
    name = "Обо мне"
    weight = 20      
  [[languages.ru.menu.main]]
    url = "#contactTitle"
    name = "Контакты"
    weight = 30


[params]    
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showMyFriends = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true



[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/andriiy.lazarenko"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/_coreer/"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/andrii-lazarenko-074ba614/"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "email"
	url = "mailto:andrew.yeremenko@gmail.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"